matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\`~]
      delimiters:
      # Ignore multiline content between YAML front matter, ex:
      # ---
      # title: "My Title"
      # ---
      - open: '(?s)^(?P<open> *-{3,})$'
        close: '^(?P=open)$'
      # Ignore stuff between {% ... %}
      - open: '\{%'
        close: '%\}'
  - pyspelling.filters.markdown:
  - pyspelling.filters.url:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8