version: '3'

# docker-compose file for development purposes only

services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --livereload #--watch --force_polling --verbose
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll